name: Flutter Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
    build:
      runs-on: macos-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
        - uses: subosito/flutter-action@v2
          with:
            flutter-version: '2.10.4'
        - run: flutter pub get
        - run: flutter test
        - run: flutter build apk
        - run: flutter build appbundle
        - name: Copy
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/release/*.apk,build/app/outputs/bundle/release/app-release.aab"
            tag: v1.0.${{github.run_number}}
            token: ${{ secrets.GITHUB_TOKEN }} # this is automatically provided by github
            # commit: ${{!github!}}